"""add effects aroma genetic_origin to strain

Revision ID: 43c6f60e699a
Revises: 7be1e169f095
Create Date: 2026-07-12 08:24:15.030899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43c6f60e699a'
down_revision: Union[str, Sequence[str], None] = '7be1e169f095'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strains', sa.Column('genetic_origin', sa.Text(), nullable=True))
    op.add_column('strains', sa.Column('effects', sa.Text(), nullable=True))
    op.add_column('strains', sa.Column('aroma', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strains', 'aroma')
    op.drop_column('strains', 'effects')
    op.drop_column('strains', 'genetic_origin')
    # ### end Alembic commands ###
